//  Copyright (C) 2019 Joshua Tyler
//
//  This library is free software; you can redistribute it and/or
//  modify it under the terms of the GNU Lesser General Public
//  License as published by the Free Software Foundation; either
//  version 2.1 of the License, or (at your option) any later version.
//  See the file LICENSE_LGPL included with this distribution for more
//  information.

VERILATOR = verilator
#VERILATOR_FLAGS = --trace --cc --exe -CFLAGS '-Wall -Wextra -g -fno-stack-protector'
VERILATOR_FLAGS = --trace --cc --exe -CFLAGS '-Wall -Wextra -g'

VERILOG_TOP = crc.v
CPP_SOURCES = test_crc.cpp

default : run

run:
	$(VERILATOR) $(VERILATOR_FLAGS) $(VERILOG_TOP) $(CPP_SOURCES)

	$(MAKE) -j 4 -C obj_dir -f Vcrc.mk

clean:
	rm -r obj_dir
